/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DadosCV;

import Compra_Venda_Telas.*;
import Principal.TelaPrincipal;
import compravenda.Compra;
import compravenda.Materia_Prima;
import compravenda.Movel;
import compravenda.Venda;
import java.util.ArrayList;
import pessoa.Cliente;
import pessoa.Fornecedor;

/**
 *
 * @author Hiury
 */
public class DadosCVTela extends javax.swing.JInternalFrame {

    /**
     * Creates new form Estoque
     */
    public ArrayList<Compra> compras = new ArrayList<Compra>();
    public ArrayList<Venda> vendas = new ArrayList<Venda>();
    public TelaPrincipal tP;

    public DadosCVTela(TelaPrincipal vai, ArrayList<Compra> comp, ArrayList<Venda> vend) {
        initComponents();
        tP = vai;
        compras = comp;
        vendas = vend;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        compra = new javax.swing.JButton();
        telaCV = new javax.swing.JDesktopPane();
        venda = new javax.swing.JButton();

        setClosable(true);
        setTitle("Realizar compra ou venda");

        compra.setBackground(new java.awt.Color(255, 168, 0));
        compra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        compra.setText("Compra");
        compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout telaCVLayout = new javax.swing.GroupLayout(telaCV);
        telaCV.setLayout(telaCVLayout);
        telaCVLayout.setHorizontalGroup(
            telaCVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        telaCVLayout.setVerticalGroup(
            telaCVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );

        venda.setBackground(new java.awt.Color(255, 168, 0));
        venda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        venda.setText("Venda");
        venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(compra, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(venda, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(telaCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(compra, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(venda, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(telaCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendaActionPerformed
        RelatorioV tela = new RelatorioV(tP, vendas);
        telaCV.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_vendaActionPerformed

    private void compraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compraActionPerformed
        RelatorioC tela = new RelatorioC(compras);
        telaCV.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_compraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton compra;
    private javax.swing.JDesktopPane telaCV;
    private javax.swing.JButton venda;
    // End of variables declaration//GEN-END:variables
}
