/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DadosCV;

import compravenda.Compra;
import compravenda.Venda;
import java.util.ArrayList;

/**
 *
 * @author Hiury
 */
public class RelatorioC extends javax.swing.JInternalFrame {

    /**
     * Creates new form Relatorio
     */
    
    ArrayList<Compra> compras = new ArrayList<Compra>();
    
    
    
    
    public RelatorioC(ArrayList<Compra> comp) {
        initComponents();
        compras = comp;
        pegaCompras();
    }
    
    
    public void pegaCompras(){
        cbCompra.addItem(" ");
        for(int i = 0; i < compras.size(); i++){
            cbCompra.addItem("Compra nº " + (i + 1));
        }
    }
    
    public void pegaDados(){
        Frete.setText(String.valueOf(compras.get(cbCompra.getSelectedIndex()).getFrete()));
        PrecoB.setText(String.valueOf(compras.get(cbCompra.getSelectedIndex()).getPrecoBruto()));
        PrecoT.setText(String.valueOf(compras.get(cbCompra.getSelectedIndex()).precoTotal));
        dataC.setText(compras.get(cbCompra.getSelectedIndex()).data);
        edtFornecedor.setText(compras.get(cbCompra.getSelectedIndex()).nomeFornecedor);
        edtProduto.setText(compras.get(cbCompra.getSelectedIndex()).nomeMP);
        edtQtd.setText(String.valueOf(compras.get(cbCompra.getSelectedIndex()).quantidade));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaC = new javax.swing.JPanel();
        edtQtd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        edtFornecedor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        edtProduto = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        PrecoB = new javax.swing.JTextField();
        Frete = new javax.swing.JTextField();
        dataC = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        PrecoT = new javax.swing.JTextField();
        entregaA = new javax.swing.JLabel();
        cbCompra = new javax.swing.JComboBox<>();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        telaC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        edtQtd.setEditable(false);
        edtQtd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        telaC.add(edtQtd, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 180, 35));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Quantidade");
        telaC.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, -1, -1));

        edtFornecedor.setEditable(false);
        edtFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        telaC.add(edtFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 256, 35));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Fornecedor");
        telaC.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Produto");
        telaC.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setText("Data de Compra");
        telaC.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 130, -1));

        edtProduto.setEditable(false);
        edtProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        telaC.add(edtProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 180, 35));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setText("Preço Bruto");
        telaC.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel13.setText("Frete");
        telaC.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        PrecoB.setEditable(false);
        PrecoB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PrecoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecoBActionPerformed(evt);
            }
        });
        telaC.add(PrecoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 180, 35));

        Frete.setEditable(false);
        Frete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        telaC.add(Frete, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 230, 35));

        dataC.setEditable(false);
        dataC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        telaC.add(dataC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 200, 35));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel14.setText("Preço Total");
        telaC.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 80, -1));

        PrecoT.setEditable(false);
        PrecoT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        telaC.add(PrecoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 200, 35));

        getContentPane().add(telaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 790, 290));

        entregaA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        entregaA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        entregaA.setText("Compra Feita");
        getContentPane().add(entregaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 210, 40));

        cbCompra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCompraActionPerformed(evt);
            }
        });
        getContentPane().add(cbCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 210, 35));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrecoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecoBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecoBActionPerformed

    private void cbCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCompraActionPerformed
        if (!" ".equals(String.valueOf(cbCompra.getSelectedItem()))) {
            pegaDados();
            telaC.setVisible(true);
        } else {
            telaC.setVisible(false);
        }
    }//GEN-LAST:event_cbCompraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Frete;
    private javax.swing.JTextField PrecoB;
    private javax.swing.JTextField PrecoT;
    private javax.swing.JComboBox<String> cbCompra;
    private javax.swing.JTextField dataC;
    private javax.swing.JTextField edtFornecedor;
    private javax.swing.JTextField edtProduto;
    private javax.swing.JTextField edtQtd;
    private javax.swing.JLabel entregaA;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel telaC;
    // End of variables declaration//GEN-END:variables
}
