/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DadosCV;

import Principal.TelaPrincipal;
import compravenda.Compra;
import compravenda.Venda;
import java.util.ArrayList;

/**
 *
 * @author Hiury
 */
public class RelatorioV extends javax.swing.JInternalFrame {

    /**
     * Creates new form Relatorio
     */
    ArrayList<Venda> vendas = new ArrayList<Venda>();
    TelaPrincipal tP;
    public int indice;

    public RelatorioV(TelaPrincipal tP, ArrayList<Venda> vend) {
        initComponents();
        this.tP = tP;
        vendas = vend;
        pegaVendas0();
        pegaVendas1();
    }

    public void pegaVendas0() {
        cbAndamento.addItem(" ");
        for (int i = 0; i < vendas.size(); i++) {
            if (vendas.get(i).status == 0) {
                cbAndamento.addItem("Compra nº " + (i + 1));
            }

        }
    }

    public void pegaVendas1() {
        cbAndamento.addItem(" ");
        for (int i = 0; i < vendas.size(); i++) {
            if (vendas.get(i).status == 1) {
                cbAndamento.addItem("Compra nº " + (i + 1));
            }

        }
    }

    public void pegaDados(int i) {
        String valor;
        valor = String.valueOf(cbAndamento.getSelectedItem()).replaceAll("[^0-9]+", "");
        indice = Integer.parseInt(valor) - 1;
        if (i == 0) {
            Acrescento.setText(String.valueOf(vendas.get(indice).acrescento));
            PrecoB.setText(String.valueOf(vendas.get(indice).getPrecoBruto()));
            PrecoT.setText(String.valueOf(vendas.get(indice).precoTotal));
            dataP.setText(vendas.get(indice).data);
            edtCliente.setText(vendas.get(indice).nomeCliente);
            edtMovel.setText(vendas.get(indice).nomeMovel);
            edtQtd.setText(String.valueOf(vendas.get(indice).quantidade));
            descon.setText(String.valueOf(vendas.get(indice).getDesconto()));
            status.setText("Em andamento");
            
        } else if (i == 1) {
            Acrescento.setText(String.valueOf(vendas.get(indice).acrescento));
            PrecoB.setText(String.valueOf(vendas.get(indice).getPrecoBruto()));
            PrecoT.setText(String.valueOf(vendas.get(indice).precoTotal));
            dataP.setText(vendas.get(indice).data);
            edtCliente.setText(vendas.get(indice).nomeCliente);
            edtMovel.setText(vendas.get(indice).nomeMovel);
            edtQtd.setText(String.valueOf(vendas.get(indice).quantidade));
            descon.setText(String.valueOf(vendas.get(indice).getDesconto()));
            status.setText("Finalizado");

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaC = new javax.swing.JPanel();
        edtQtd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        edtCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        edtMovel = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        PrecoB = new javax.swing.JTextField();
        descon = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        PrecoT = new javax.swing.JTextField();
        Acrescento = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        finaliza = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        dataP = new javax.swing.JTextField();
        entregaA = new javax.swing.JLabel();
        cbAndamento = new javax.swing.JComboBox<>();
        entregaA1 = new javax.swing.JLabel();
        cbFinalizada = new javax.swing.JComboBox<>();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        telaC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        edtQtd.setEditable(false);
        edtQtd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        telaC.add(edtQtd, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 180, 35));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Quantidade");
        telaC.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, -1, -1));

        edtCliente.setEditable(false);
        edtCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        telaC.add(edtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 256, 35));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Cliente");
        telaC.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Movel");
        telaC.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setText("Status");
        telaC.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 130, -1));

        edtMovel.setEditable(false);
        edtMovel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        telaC.add(edtMovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 180, 35));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setText("Preço Bruto");
        telaC.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel13.setText("Desconto");
        telaC.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        PrecoB.setEditable(false);
        PrecoB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PrecoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecoBActionPerformed(evt);
            }
        });
        telaC.add(PrecoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 180, 35));

        descon.setEditable(false);
        descon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        telaC.add(descon, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 230, 35));

        status.setEditable(false);
        status.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        status.setText("Em andamento");
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        telaC.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 200, 35));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel14.setText("Preço Total");
        telaC.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 80, -1));

        PrecoT.setEditable(false);
        PrecoT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        telaC.add(PrecoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 200, 35));

        Acrescento.setEditable(false);
        Acrescento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        telaC.add(Acrescento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 230, 35));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel15.setText("Acrescento");
        telaC.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        finaliza.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        finaliza.setText("Finalizar Pedido");
        finaliza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizaActionPerformed(evt);
            }
        });
        telaC.add(finaliza, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, -1, 35));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel16.setText("Data do Pedido");
        telaC.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 130, -1));

        dataP.setEditable(false);
        dataP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        telaC.add(dataP, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 200, 35));

        getContentPane().add(telaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 790, 300));

        entregaA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        entregaA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        entregaA.setText("Pedido em Andamento");
        getContentPane().add(entregaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 210, 40));

        cbAndamento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbAndamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAndamentoActionPerformed(evt);
            }
        });
        getContentPane().add(cbAndamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 210, 35));

        entregaA1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        entregaA1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        entregaA1.setText("Pedido Finalizado");
        getContentPane().add(entregaA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 210, 40));

        cbFinalizada.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbFinalizada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFinalizadaActionPerformed(evt);
            }
        });
        getContentPane().add(cbFinalizada, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 210, 35));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrecoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecoBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecoBActionPerformed

    private void cbAndamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAndamentoActionPerformed
        if (!" ".equals(String.valueOf(cbAndamento.getSelectedItem()))) {
            pegaDados(0);
            telaC.setVisible(true);
        } else {
            telaC.setVisible(false);
        }
    }//GEN-LAST:event_cbAndamentoActionPerformed

    private void cbFinalizadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFinalizadaActionPerformed
        if (!" ".equals(String.valueOf(cbAndamento.getSelectedItem()))) {
            pegaDados(1);
            telaC.setVisible(true);
        } else {
            telaC.setVisible(false);
        } // TODO add your handling code here:
    }//GEN-LAST:event_cbFinalizadaActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void finalizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizaActionPerformed
       vendas.get(indice).status = 1;
       pegaVendas0();
       pegaVendas1();
       tP.vendas = this.vendas;
    }//GEN-LAST:event_finalizaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Acrescento;
    private javax.swing.JTextField PrecoB;
    private javax.swing.JTextField PrecoT;
    private javax.swing.JComboBox<String> cbAndamento;
    private javax.swing.JComboBox<String> cbFinalizada;
    private javax.swing.JTextField dataP;
    private javax.swing.JTextField descon;
    private javax.swing.JTextField edtCliente;
    private javax.swing.JTextField edtMovel;
    private javax.swing.JTextField edtQtd;
    private javax.swing.JLabel entregaA;
    private javax.swing.JLabel entregaA1;
    private javax.swing.JButton finaliza;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField status;
    private javax.swing.JPanel telaC;
    // End of variables declaration//GEN-END:variables
}
