/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MP_Mov_Telas;

import MP_Mov_Telas.CadMov;
import MP_Mov_Telas.CadMP;
import Principal.TelaPrincipal;
import compravenda.Materia_Prima;
import compravenda.Movel;
import java.util.ArrayList;

/**
 *
 * @author Hiury
 */
public class MatMov extends javax.swing.JInternalFrame {

    /**
     * Creates new form Estoque
     */
    ArrayList<Materia_Prima> materias = new ArrayList<Materia_Prima>();
    ArrayList<Movel> moveis = new ArrayList<Movel>();
    TelaPrincipal teste;
    CadMP materiaprima;
    CadMov movelTela;

    public MatMov(TelaPrincipal vai, ArrayList<Materia_Prima> mp, ArrayList<Movel> mov) {
        initComponents();
        teste = vai;
        materias = mp;
        moveis = mov;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        matP = new javax.swing.JButton();
        tela3 = new javax.swing.JDesktopPane();
        estoque2 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastro de Matéria e Móveis");
        setPreferredSize(new java.awt.Dimension(1180, 447));

        matP.setBackground(new java.awt.Color(255, 168, 0));
        matP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        matP.setText("Matéria Prima");
        matP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matPActionPerformed(evt);
            }
        });

        tela3.setPreferredSize(new java.awt.Dimension(800, 408));

        javax.swing.GroupLayout tela3Layout = new javax.swing.GroupLayout(tela3);
        tela3.setLayout(tela3Layout);
        tela3Layout.setHorizontalGroup(
            tela3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        tela3Layout.setVerticalGroup(
            tela3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );

        estoque2.setBackground(new java.awt.Color(255, 168, 0));
        estoque2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        estoque2.setText("Móveis");
        estoque2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estoque2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(matP, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estoque2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(tela3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tela3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(matP, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(estoque2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void matPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matPActionPerformed
        materiaprima = new CadMP(teste, materias);
        tela3.add(materiaprima);
        materiaprima.setVisible(true);
    }//GEN-LAST:event_matPActionPerformed

    private void estoque2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estoque2ActionPerformed
        movelTela = new CadMov(teste, materias, moveis);
        tela3.add(movelTela);
        movelTela.setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_estoque2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton estoque2;
    private javax.swing.JButton matP;
    private javax.swing.JDesktopPane tela3;
    // End of variables declaration//GEN-END:variables
}
