/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import compravenda.Materia_Prima;
import java.util.ArrayList;

/**
 *
 * @author Hiury
 */
public class EstoqueTela extends javax.swing.JInternalFrame {

    /**
     * Creates new form Estoque
     */
    EstoqueMP estoqueMP;
    ArrayList<Materia_Prima> materias = new ArrayList<Materia_Prima>();
    TelaPrincipal teste2;

    public EstoqueTela(TelaPrincipal vai, ArrayList<Materia_Prima> materia) {
        initComponents();
        estoque1.setText("<html> Estoque <> Matéria Prima<html>");
        estoque2.setText("<html> Estoque <> Móveis<html>");

        teste2 = vai;
        materias = materia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        estoque1 = new javax.swing.JButton();
        rel = new javax.swing.JButton();
        telaE = new javax.swing.JDesktopPane();
        estoque2 = new javax.swing.JButton();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1180, 447));

        estoque1.setBackground(new java.awt.Color(255, 168, 0));
        estoque1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        estoque1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estoque1ActionPerformed(evt);
            }
        });

        rel.setBackground(new java.awt.Color(255, 168, 0));
        rel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rel.setText("Relatório");

        telaE.setPreferredSize(new java.awt.Dimension(800, 408));

        javax.swing.GroupLayout telaELayout = new javax.swing.GroupLayout(telaE);
        telaE.setLayout(telaELayout);
        telaELayout.setHorizontalGroup(
            telaELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        telaELayout.setVerticalGroup(
            telaELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );

        estoque2.setBackground(new java.awt.Color(255, 168, 0));
        estoque2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        estoque2.setText("jButton2");
        estoque2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estoque2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(estoque1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estoque2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rel, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(telaE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(telaE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(estoque1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(estoque2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(rel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void estoque1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estoque1ActionPerformed
        estoqueMP = new EstoqueMP(teste2, materias);
        telaE.add(estoqueMP);
        estoqueMP.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_estoque1ActionPerformed

    private void estoque2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estoque2ActionPerformed
                     
    }//GEN-LAST:event_estoque2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton estoque1;
    private javax.swing.JButton estoque2;
    private javax.swing.JButton rel;
    private javax.swing.JDesktopPane telaE;
    // End of variables declaration//GEN-END:variables
}
