/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estoqueTelas;

import Principal.TelaPrincipal;
import compravenda.Materia_Prima;
import compravenda.Movel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hiury
 */
public class DadosMovel extends javax.swing.JInternalFrame {

    /**
     * Creates new form DadosMovel
     */
    TelaPrincipal tP;
    ArrayList<Materia_Prima> materiasP = new ArrayList<Materia_Prima>();
    ArrayList<Movel> moveis = new ArrayList<Movel>();
    public int rowCount = 0;

    public DadosMovel(TelaPrincipal tP, ArrayList<Materia_Prima> mP, ArrayList<Movel> mov) {
        initComponents();
        this.tP = tP;
        materiasP = mP;
        moveis = mov;
        pr.setVisible(false);

        pegaMP();
    }

    public void pegaMP() {

        movCombo.addItem(" ");
        for (int i = 0; i < moveis.size(); i++) {
            movCombo.addItem(moveis.get(i).nome);
        }

    }

    public void pegaDados() {
        for (int i = 0; i < moveis.size(); i++) {
            if (String.valueOf(movCombo.getSelectedItem()).equals(moveis.get(i).nome)) {
                nomeMovField.setText(moveis.get(i).nome);

                for (int j = 0; j < moveis.get(i).materiaP.size(); j++) {
                    rowCount++;
                    ((DefaultTableModel) tabela.getModel()).setRowCount(rowCount);
                    tabela.setValueAt(moveis.get(i).materiaP.get(j), rowCount - 1, 0);
                    tabela.setValueAt(moveis.get(i).qtd.get(j), rowCount - 1, 1);
                    tabela.setValueAt(moveis.get(i).qtd.get(j) * pegaPrecoUnit(i,j), rowCount - 1, 2);
                }

            }
        }

    }
    
    public float pegaPrecoUnit(int posicao, int posicao2){
        float valorUnit = 0;
        for(int i = 0; i < materiasP.size(); i++){
            if(materiasP.get(i).nome.equals(moveis.get(posicao).materiaP.get(posicao2))){
                valorUnit = materiasP.get(i).precoUnit;
            }
        }
        
        return valorUnit;
        
        
    }

    public void calculaCustoTotal() {
        float custo = 0;
        for (int i = 0; i < tabela.getRowCount(); i++) {
            custo = custo + Float.parseFloat(String.valueOf(tabela.getValueAt(i, 2)));
        }
        custoTotal.setText(String.valueOf(custo));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        movCombo = new javax.swing.JComboBox<>();
        pr = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        nomeMovField = new javax.swing.JTextField();
        del = new javax.swing.JButton();
        alt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        custoTotal = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Movel");

        movCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movComboActionPerformed(evt);
            }
        });

        pr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Nome do Movel");
        pr.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));
        pr.add(nomeMovField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 150, 30));

        del.setText("Deletar");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        pr.add(del, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 90, 30));

        alt.setText("Alterar");
        alt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altActionPerformed(evt);
            }
        });
        pr.add(alt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 90, 30));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matéria Prima", "Quantidade", "Preço Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);

        pr.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 500, 160));

        custoTotal.setText(" ");
        pr.add(custoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 140, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Custo de produção");
        pr.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(movCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(315, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pr, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(370, 370, 370))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(6, 6, 6)
                .addComponent(movCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pr, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void movComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movComboActionPerformed
        if (!" ".equals(String.valueOf(movCombo.getSelectedItem()))) {
            pr.setVisible(true);
            pegaDados();
            calculaCustoTotal();
        } else {
            pr.setVisible(false);
        }
    }//GEN-LAST:event_movComboActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed

    }//GEN-LAST:event_delActionPerformed

    private void altActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altActionPerformed

    }//GEN-LAST:event_altActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alt;
    private javax.swing.JLabel custoTotal;
    private javax.swing.JButton del;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> movCombo;
    private javax.swing.JTextField nomeMovField;
    private javax.swing.JPanel pr;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
